apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/er-aws-rds?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "20"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  labels:
    appstudio.openshift.io/application: er-aws-rds-main
    appstudio.openshift.io/component: er-aws-rds-main
    pipelines.appstudio.openshift.io/type: build
  name: er-aws-rds-main-on-push
  namespace: app-sre-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/app-sre-tenant/er-aws-rds-main/er-aws-rds-main:{{revision}}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: target-stage
    value: prod
  - name: build-platforms
    value:
    - linux/x86_64
    # - linux-m2xlarge/arm64
  taskRunSpecs:
  - pipelineTaskName: build-container
    stepSpecs:
    - name: build
      computeResources:
        requests:
          memory: 20Gi
        limits:
          memory: 20Gi
  - pipelineTaskName: ecosystem-cert-preflight-checks
    stepSpecs:
    - name: check-container
      computeResources:
        requests:
          memory: 4Gi
        limits:
          memory: 4Gi
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/app-sre/shared-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/multi-arch-build-pipeline.yaml
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
